fixes salt bridge detection for nucleic acid receptors
pharmai/plip pull request #127
Opened 2022-03-31 13:45 UTC by sungekim

This change fixes the issue of the salt bridge not getting detected when nucleic acids are treated as a part of the receptor.

On the receptor side, now it recognizes nucleic acid residues and looks for the negative charge in the phosphate backbone, which are possible candidates to form salt bridges.

Thank you.

2022-03-31 15:51 UTC, fkaiserbio requested changes
Dear sungekim,

thanks for this great contribution! I would kindly ask you a few things before we can merge this:

- don't use hard-coded residue names of DNA/RNA, there are constants for use in https://github.com/pharmai/plip/blob/99df154d831cea92900ff7daf0e3e38f689ec89a/plip/basic/config.py#L70
- please add a comment in line 972, which property magic number 9 belongs to (sugar phosphate) or use verbose Enum representation if possible
- please, if anyhow possible, write a unit test where you detect an expected interaction properly in a new test class `plip/test/test_salt_bridges.py`

2022-04-05 09:53 UTC, sungekim commented
Hello,

I have changed DNA/RNA residue names to constant and added a comment that is looking for a negative charge in sugar phosphate. Also, I wrote a unit test for the salt bridge detection, specifically for nucleic acids as part of the receptor.

Please confirm this change, hopefully, I didn't miss anything.
Thank you!

2022-04-05 12:02 UTC, fkaiserbio approved these changes

2022-04-05 12:02 UTC, merged

2022-04-05 12:03 UTC, fkaiserbio commented
Thanks for the contribution! Please make sure to sign commits for any future PRs. See: https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification